name: CI Testing / Fuzz Testing
on: [push, pull_request]

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rust-src
          override: true

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Check fuzz directory exists
        run: |
          if [ ! -d fuzz ]; then
            echo "No fuzz directory found, skipping fuzz tests."
            exit 0
          fi

      - name: Run fuzz tests
        run: |
          cd fuzz
          cargo fuzz run distances -- -max_total_time=60
        env:
          RUSTFLAGS: -C debug-assertions=no
          RUST_BACKTRACE: full
